// Generated by scripts/embed-migrations.ts from drizzle/*.sql. Do not edit.
export interface Migration {
  name: string;
  statements: string[];
}

export const MIGRATIONS: Migration[] = [
  {
    "name": "0000_init",
    "statements": [
      "CREATE TABLE \"artifacts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"run_id\" text,\n\t\"phase_id\" text,\n\t\"type\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"supersedes\" text,\n\t\"created_at\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"audit\" (\n\t\"seq\" bigserial PRIMARY KEY NOT NULL,\n\t\"id\" text NOT NULL,\n\t\"at\" text NOT NULL,\n\t\"actor_id\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"decisions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"run_id\" text,\n\t\"kind\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"memory_records\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"scope_type\" text NOT NULL,\n\t\"scope_id\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"projects\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"runs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"pack_id\" text NOT NULL,\n\t\"project_id\" text,\n\t\"title\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"idempotency_key\" text,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"steps\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"run_id\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE TABLE \"usage_entries\" (\n\t\"seq\" bigserial PRIMARY KEY NOT NULL,\n\t\"run_id\" text NOT NULL,\n\t\"at\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE INDEX \"artifacts_run_idx\" ON \"artifacts\" USING btree (\"run_id\");",
      "CREATE INDEX \"artifacts_supersedes_idx\" ON \"artifacts\" USING btree (\"supersedes\");",
      "CREATE INDEX \"audit_action_idx\" ON \"audit\" USING btree (\"action\");",
      "CREATE INDEX \"audit_actor_idx\" ON \"audit\" USING btree (\"actor_id\");",
      "CREATE INDEX \"decisions_run_idx\" ON \"decisions\" USING btree (\"run_id\");",
      "CREATE INDEX \"decisions_status_idx\" ON \"decisions\" USING btree (\"status\");",
      "CREATE INDEX \"memory_scope_idx\" ON \"memory_records\" USING btree (\"scope_type\",\"scope_id\");",
      "CREATE INDEX \"memory_status_idx\" ON \"memory_records\" USING btree (\"status\");",
      "CREATE INDEX \"runs_status_idx\" ON \"runs\" USING btree (\"status\");",
      "CREATE INDEX \"runs_pack_idx\" ON \"runs\" USING btree (\"pack_id\");",
      "CREATE INDEX \"runs_project_idx\" ON \"runs\" USING btree (\"project_id\");",
      "CREATE INDEX \"runs_created_idx\" ON \"runs\" USING btree (\"created_at\");",
      "CREATE UNIQUE INDEX \"runs_idem_idx\" ON \"runs\" USING btree (\"idempotency_key\");",
      "CREATE INDEX \"steps_run_idx\" ON \"steps\" USING btree (\"run_id\");",
      "CREATE INDEX \"usage_run_idx\" ON \"usage_entries\" USING btree (\"run_id\");"
    ]
  },
  {
    "name": "0001_events",
    "statements": [
      "CREATE TABLE \"events\" (\n\t\"seq\" bigserial PRIMARY KEY NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"at\" text NOT NULL,\n\t\"run_id\" text,\n\t\"subject_type\" text NOT NULL,\n\t\"subject_id\" text NOT NULL,\n\t\"data\" jsonb NOT NULL\n);",
      "CREATE INDEX \"events_run_idx\" ON \"events\" USING btree (\"run_id\",\"seq\");",
      "CREATE INDEX \"events_type_idx\" ON \"events\" USING btree (\"type\",\"seq\");",
      "CREATE INDEX \"events_subject_idx\" ON \"events\" USING btree (\"subject_type\",\"subject_id\",\"seq\");"
    ]
  }
];
