// Generates src/generated/operations.ts from the contract route table: one typed entry per operation.
// Usage: node scripts/generate.mjs [--check]   (build @kramahq/contract first)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ROUTES } from '@kramahq/contract';
import { z } from 'zod';

const OUT = fileURLToPath(new URL('../src/generated/operations.ts', import.meta.url));

/** JSON Schema (draft 2020-12, the subset zod emits) to a TypeScript type expression. */
export function tsType(s) {
  if (s === true || (s && typeof s === 'object' && Object.keys(s).length === 0)) return 'unknown';
  if (s === false) return 'never';
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(' | ');
  const union = s.anyOf ?? s.oneOf;
  if (union) return union.map((u) => paren(tsType(u))).join(' | ');
  if (Array.isArray(s.type)) return s.type.map((t) => tsType({ ...s, type: t })).join(' | ');
  switch (s.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      if (s.prefixItems) return `[${s.prefixItems.map(tsType).join(', ')}]`;
      return `${paren(tsType(s.items ?? {}))}[]`;
    case 'object': {
      const props = Object.entries(s.properties ?? {});
      const required = new Set(s.required ?? []);
      const parts = props.map(
        ([k, v]) => `${JSON.stringify(k)}${required.has(k) ? '' : '?'}: ${tsType(v)}`,
      );
      const extra = s.additionalProperties;
      if (extra && extra !== false) parts.push(`[key: string]: ${tsType(extra)}`);
      if (parts.length === 0)
        return extra === false ? 'Record<string, never>' : 'Record<string, unknown>';
      return `{ ${parts.join('; ')} }`;
    }
    default:
      return 'unknown';
  }
}
const paren = (t) => (/[|&]/.test(t) && !/^[{(]/.test(t) ? `(${t})` : t);

const schemaOf = (zod, io) => {
  const { $schema, ...rest } = z.toJSONSchema(zod, {
    io,
    unrepresentable: 'any',
    reused: 'inline',
  });
  void $schema;
  return rest;
};
const paramNames = (path) => [...path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
const BINARY = (r) => !r.response && r.status !== 204;

export function render() {
  const lines = [
    '// Generated by `pnpm -F @kramahq/sdk generate` from the route table in @kramahq/contract. Do not edit.',
    '',
    '/** Static facts about every operation, keyed by operationId. */',
    'export const OPERATIONS = {',
  ];
  const types = [
    '',
    '/** The request and response shapes of every operation. */',
    'export interface OperationTypes {',
  ];
  for (const r of ROUTES) {
    const params = paramNames(r.path);
    const kind = r.stream ? 'stream' : BINARY(r) ? 'raw' : r.status === 204 ? 'empty' : 'json';
    lines.push(
      `  ${r.operationId}: { method: '${r.method}', path: '${r.path}', tag: '${r.tag}', perm: ${JSON.stringify(r.perm)}, kind: '${kind}', status: ${r.status ?? 200}, params: ${JSON.stringify(params)}, idempotent: ${!!r.idempotent}, ifMatch: ${!!r.ifMatch}, cut1: ${r.cut1} },`,
    );
    const t = [
      `params: ${params.length ? `{ ${params.map((p) => `${p}: string`).join('; ')} }` : 'undefined'}`,
      `query: ${r.query ? tsType(schemaOf(r.query, 'input')) : 'undefined'}`,
      `body: ${r.body ? tsType(schemaOf(r.body, 'input')) : 'undefined'}`,
      `response: ${r.response ? tsType(schemaOf(r.response, 'output')) : kind === 'raw' ? 'Response' : 'void'}`,
    ];
    types.push(
      `  /** ${r.method} ${r.path}: ${r.summary} */`,
      `  ${r.operationId}: { ${t.join('; ')} };`,
    );
  }
  lines.push('} as const;', ...types, '}', '');
  return lines.join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = render();
  if (process.argv.includes('--check')) {
    if (readFileSync(OUT, 'utf8') !== out) {
      console.error('src/generated/operations.ts is stale: run `pnpm -F @kramahq/sdk generate`');
      process.exit(1);
    }
  } else writeFileSync(OUT, out);
}
