// Embeds drizzle/*.sql into src/migrations.generated.ts so the bundle needs no files on disk.
// Usage: node scripts/embed-migrations.ts [--check]
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'drizzle');
const out = join(root, 'src', 'migrations.generated.ts');

const files = readdirSync(dir)
  .filter((f) => f.endsWith('.sql'))
  .sort();
const entries = files.map((f) => {
  const sql = readFileSync(join(dir, f), 'utf8').replace(/\r\n/g, '\n');
  return {
    name: f.replace(/\.sql$/, ''),
    statements: sql
      .split('--> statement-breakpoint')
      .map((s) => s.trim())
      .filter(Boolean),
  };
});

const body = `// Generated by scripts/embed-migrations.ts from drizzle/*.sql. Do not edit.\nexport interface Migration {\n  name: string;\n  statements: string[];\n}\n\nexport const MIGRATIONS: Migration[] = ${JSON.stringify(entries, null, 2)};\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    /* missing */
  }
  if (current !== body) {
    console.error(
      'src/migrations.generated.ts is out of date. Run: pnpm -F @kramahq/store db:generate',
    );
    process.exit(1);
  }
} else {
  writeFileSync(out, body);
  console.log(`Embedded ${entries.length} migration(s)`);
}
